### ISSUE TITLE
Running your model

### ISSUE THREAD

**Issue by HappyDay-design** [CorinnaJiang/DQN-SUMO-RoutingPlanning#3]
Thank you for sharing your code

Could you give details about running your code?  Do you have any paper related to your code

**Comment by HappyDay-design** [comment]
When running `python train.py`, it had errors

Traceback (most recent call last):
  File "/home/osboxes/Desktop/DQN-SUMO-RoutingPlanning/train.py", line 13, in <module>
    from base import MyEnv
  File "/home/osboxes/Desktop/DQN-SUMO-RoutingPlanning/base.py", line 9, in <module>
    from flow.envs import Env
ModuleNotFoundError: No module named 'flow'
